#+TITLE: Seminar_paper_overview




* Todo
- Gibts statistiken zum vergleichen?
- References einbauen
- Grafik für beispiel einbauen
- sag das paper in thematik einführen soll
- gibt noch mathematische erklärungen










Betreff: Frage zur Seitenzahl meiner wissenschaftlichen Ausarbeitung

Liebes Seminar Team,

Ich wollte fragen wie streng die mindest Seitenanzahl der Ausarbeitung ist, da auf den Folien auch zwei verschiedene Angaben stehen.
Einmal 8-10 Seiten und dann einmal mind. 10 Seiten.

Außerdem wollte ich fragen ob sich diese Zahl nur auf die mindest Seiten Zahl oder auf die Seitenzahl von geschriebenen Text bezieht.
Also ob man zum Beispiel die 10. Seite voll haben muss oder ab es reicht wenn die 10. Seite nur zur hälfte beschrieben ist.

Falls die 10 Seiten unbedingt gefüllt werden müssten, hättet ihr noch irgendwelche Punkte die ich noch in meiner Ausarbeitung noch einbringen könnte?
Derzeit bin ich insgesamt bei 8.5 Seiten geschriebenen Inhalt und bin am Ende von meinen bisherigen Recherchen.

Im Anhang habe ich mal meine erste Draft von meiner Ausarbeitung hinzugefügt. Ich müsste noch einige Sachen überarbeiten, jedoch sollte das Große und Ganze schonmal stehen.


Vielen Dank im Voraus für Eure Hilfe und Verständnis.

Lg
Alfred



* Gliederung

1. Abstract (3. )
   - linear equations are basic problem of maths
   - a lot of problems can be solved with this
   - Linear equations to be solved faster via HHL
   - used as a subroutine

Kürzel wie QPE, IQPE HHL, spezifizieren

1. Introduction
   1. Why is this algorihtm important?
   2. What problems can be solved?
   3. What does the algorithm promise?
   4. Classical method v quantum mechanical method

2. Idea/Overview of the algorihtm (1. ; 4.)
   a) Quantum Circuit
      - explain intuitively the phases of the algorithm
      - explain all registers (a,b,c-register)

   b) The Overview
      - A is Hamiltonian (if not Hamiltonian then ...)
      - A can be split up outer spectral decomposition (eigenvectors and eigenvalues) ...
      - same für A^-1 ...
      - b can be written in the eigenbasis of A ...
      - x can be written as...

3. The Algorithm (1. ; 3. )
   a) State preparation
   b) Quantum Phase Estimation
      - State of circuit contains eigenwerte/values
   c) Inversion of the eigenvalues
   d) Inverse Quantum Phase Estimation
   e) Measurement

4. Discussion/Evaluation
   a) Gaussian Elimination
   b) Classical v. Quantum (4. ;)
   c) Error analysis
   d) Limitations
      1. fast state preparation
      2. low condition number
      3. sparseness and error
      4. readout of |x>
   e) Improvements (2.)
      1. Varibale time amplitude amplification (2.)

5. Conclusion



* Quellen
1. Step-by-Step
2. Primer
3. Hassan_fin
4. HHL 2009

* Misc
1. Mathematical fundamentals
   1. Hermitian matrics
   2. Spectral decomposition
   3. Kronecker delta
   4. Entangled states
   5. Types of Encoding
      a) Hamiltonian Encoding
      b) Amplitude Encoding
      c) Basis Encoding



* Email
  - Wie mathematisch?
  - Beispiel?
  - Sachen wie QPE oder Fourier transformation erklären?
  - Soll ich einfach eine Draft vom Inhaltsverzeichnis schicken????

** Antwort
Sehr guter Vortrag mit kleineren Fehlern.
Der konkrete Output des Algorithmus könnte klarer definiert werden.
Die Motivation wie der Algorithmus vorgeht, dass man über Eigenvektoren rechnet, sollte besser veranschaulicht werden. Das Beispiel konnte dies nicht wirklich veranschaulichen, da konkrete Zahlenwerte genutzt wurden.

Wie ist der output genau definiert?
Was ist die motivation dahinter über die eigenwerte/eigenvektoren zu rechnen

** Fragen
  Ich hätte ein paar Fragen.
  Ich habe versucht die Präsentation so gut wie möglich ohne Formeln und mathematische Erklärung zu machen, da ich davon ausgegangen bin, dass


  Die Präsentation war eher dazu da

** Text
Liebes Seminar Team,

ich habe den HHL-Algorithmus als Thema und hätte noch ein paar Fragen zur schriftlichen Ausarbeitung.

In meiner Präsentation habe ich viele mathematische Erklärungen ausgelassen, da die Präsentation sonst zu lang und trocken geworden wäre.

Mir war es wichtig, mich in der Präsentation auf die allgemeine Funktionsweise und Intuition des Algorithmus zu konzentrieren. Alles andere spezifischere sollte man ja in der Ausarbeitung nachlesen können so wie ich das verstanden habe.

Mein Frage wäre jetzt, wie mathematisch und detailiert das ganze sein müsste.

1) Soll ich beispielsweise einige mathematische Definitionen/Anforderungen im Voraus erklären? (Hermitische Matrix, Unitary, Entanglement, ...)

2) Wäre eine detaillierte Durchrechnung mit einem einfachen Beispiel (ähnlich wie in der Präsentation) für das Verständnis nötig oder genügt es, die Schritte rein mathematisch zu erläutern (nur mit Formeln, ohne explizites Beispiel)?

3) Wie sollte das Verhältnis zwischen formalen Erklärungen und der Auswertung/Laufzeitanalyse sein?

4) Gibt es noch Punkte, die in meiner Präsentation gefehlt haben, die ich noch einbringen sollte?

Ich danke Euch im Voraus für eure Unterstützung und freue Mich auf euer Feedback!

Liebe Grüße,
Alfred






Liebes Seminar Team,

ich hab den HHL Algorithmus als Thema und hätte noch ein paar Fragen zur schriftlichen Ausarbeitung.

In meiner Präsentation habe sehr viel Mathematische Erklärungen weggelassen, da die Präsentation sonst viel zu lang trocken gewesen wäre.

Mir war es in der Präsentation wichtig mich die allgemeine Funktionsweise und Intuition vom Algorithmus zu fokussieren. Alles andere spezifischere sollte man ja in der Ausarbeitung nachlesen können so wie ich das verstanden habe.

Mein Frage wäre jetzt wie mathematisch und detailiert das ganze jetzt sein müsste.

1) Soll ich zum Beispiel ein paar Mathematische Definitionen/Anforderungen im Vorhinein erklären? (Hermitische Matrix, Unitary, Entanglement,...)

2) Wäre ein detailiertes durchrechnen mit einem einfachen Beispiel (ähnlich wie in der Präsentation) für das Verständnis nötig oder reicht es wenn ich die Schritte rein mathematisch durchgehen (nur mit Formeln ohne explizites Beispiel)?

3) Wie soll das Verhältnis von Formalen Erklärungen zur Auswertung/Laufzeitanalye sein?

4) Gibt es noch Punkte die in meiner Präsentation gefehlt haben die ich noch einbringen sollte?


Liebe Grüße
Name
