
#+TITLE: Text_hhl

1. Idea/Overview of the algorihtm (1. ; 4.)

   The following section will describe how the algorithm works in general.
   Then it will roughly sketch the steps of the algorthm.
   After that it will describe a short mathematical explanation to further increase understanding.

   a) Problem statement
      Given an NxN hamiltonian matrix A and a vector b, we want to solve for the vector x such that
      ...
      This problem can be rewritten as
      ...

      As described earlier the hermitian matrix A^-1 can also decomposed into its spectral decomposition. A can thus be written as a linear combination outer products of its eigenvectors ... ... weighted by its eigenvalues, lambda.

      This means that if we can find the eigenvalues and eigenvectors of A we can then solve the linear equation quite easily. Classical solutions involving spectral decomposition are not faster than other algorithm such as Gaussian Elimination [quelle]. But estimating eigenvalues and eingewerte can be performed quite efficiently by quantum techniques.

      In the quantum version the formula look like this.
      ...
      where |b> and |x> are the quantum state of the b and x vector respectively.

      Note that |x> is just a quantum state. We can not read every element to achieve the x vector. But as mentioned earlier, we are only interested in an approximation of the expectation value of some operator on x.

   b) Quantum Circuit

    Registers:
      The figure above shows the schematic of a simple quantum circuit for the HHL algorithm.
      We have three registers which describe different sets of qubits in the quantum circuit.
      The b-register contains the b vector which is encoded into a quantum state |b>. After the whole HHL procedure is done the b-register will contain the solution state |x>.

      The c-register, oftentimes refered to as the clock-register, is used for the quantum phase estimation part. It is related to the time (clock) of the controlled rotation of the qubits and will store the eigenvalues after performing QPE.

      The a-register contains the ancilla qubit. It is used for the inversion of the eigenvalues and will be explained in detail later on.



    Phases:
      The procedure of the quantum circuit can be split into 4 phases:
      Test
      1. State preparation
      2. Quantum phase estimation (QPE)
      3. Inversion of eigenvalues
      4. Inverse quantum phase estimation (IQPE)

      In the state preparation phase, the b vector will be encoded into a quantum state |b> and the A matrix will be encoded as a hamiltonian, which is a unitary operator
      U=eiAt into the QPE and IQPE operations.

      The Quantum phase estimation will then calculate the eigenvalues and eigenvectors of the A matrix.

      Then we invert the eigenvalues through rotary operations. Unfortunately, these operations have a probability to fail, as they are not unitary operators.
      The ancilla bit will either collapse to |0> or |1> for failure and success respectively.
      If the rotation is not successfull, the procedure has to be repeated.
      If the rotation was successfull we can continue the procedure.


   c) The Overview
      - A is Hamiltonian (if not Hamiltonian then ...)
      - A can be split up outer spectral decomposition (eigenvectors and eigenvalues) ...
      - same für A^-1 ...
      - b can be written in the eigenbasis of A ...
      - x can be written as...
